cmake_minimum_required(VERSION 3.0)
project(main)

# 配置编译选项
set(CMKE_CXX_FLAGS ${CMKE_CXX_FLAGS} -g)

# 配置头文件搜索路径
# include_directories()

# 配置库文件搜索路径
# link_directories()

# 设置需要编译的源文件列表
set(SRC_LISTS ./muduo_server.cpp)

# 把.指定路径下的所有源文件名字放入变量名SRC_LISTS中
# aux_source_directory(. SRC_LISTS)

add_executable(server ${SRC_LISTS})

# 表示server这个目标程序，需要链接muduo_net muduo_base pthread这三个库文件
target_link_libraries(server muduo_net muduo_base pthread)
 




